### ISSUE TITLE
Calling hal.__version__ crashes the code

### ISSUE THREAD

**Issue by Trent1048** [robotpy/robotpy-hal#3]
After running the command `py -3 -m pip uninstall robotpy-hal-sim robotpy-hal-base` as suggested on the robotpy documentation website, the hal folder is missing `__init__.py` so my code crashes when it gets to `logger.info("HAL version %s", hal.__version__)` in `_log_versions()` because `module 'hal' has no attribute '__version__'`

**Comment by virtuald** [comment]
You need to then install the RobotPy 2020 components (eg, `py -m pip install -U pyfrc`), which should install `robotpy-hal` as part of that.

**Comment by virtuald** [comment]
Updated documentation at https://robotpy.readthedocs.io/en/stable/2020_notes.html#upgrading-from-prior-years

**Comment by Trent1048** [comment]
That did not work.

**Comment by Trent1048** [comment]
The same issue still comes up and I am still missing `__init__.py` from the hal folder.

**Comment by virtuald** [comment]
What is the output of `py -m pip list`?

**Comment by Trent1048** [comment]
```
Package                  Version
------------------------ ----------
astroid                  2.3.3
atomicwrites             1.3.0
attrs                    19.3.0
bcrypt                   3.1.7
cffi                     1.13.2
colorama                 0.4.3
cryptography             2.8
header2whatever          0.4.1
isort                    4.3.21
Jinja2                   2.11.0
lazy-object-proxy        1.4.3
MarkupSafe               1.1.1
mccabe                   0.6.1
more-itertools           8.2.0
packaging                20.1
paramiko                 2.7.1
Pint                     0.10.1
pip                      20.0.2
pluggy                   0.13.1
ply                      3.11
py                       1.8.1
pycparser                2.19
pydantic                 1.4
pyfrc                    2020.0.0
pygame                   1.9.6
pylint                   2.4.4
PyNaCl                   1.3.0
pynetconsole             2.0.2
pynetworktables          2020.0.1
pyntcore                 2020.1.2.3
pyparsing                2.4.6
pytest                   5.3.5
PyYAML                   5.3
remi                     2020.1.16
robotpy-build            2020.0.25
robotpy-cppheaderparser  5.0.1
robotpy-hal              2020.1.2.3
robotpy-halsim-gui       2020.1.2.2
robotpy-installer        2020.0.2
robotpy-navx             2020.0.1
robotpy-rev              2020.0.0
robotpy-wpilib-utilities 2020.0.3
robotpy-wpiutil          2020.1.2.2
schematics               2.1.0
setuptools               45.1.0
setuptools-scm           3.3.3
six                      1.14.0
sphinxify                0.5.1
toml                     0.10.0
toposort                 1.5
wcwidth                  0.1.8
wpilib                   2020.1.2.3
wrapt                    1.11.2
```

**Comment by virtuald** [comment]
Hm, that should definitely work. Maybe try uninstalling robotpy-hal and reinstalling?

```
py -m pip uninstall robotpy-hal
py -m pip install -U robotpy-hal
```

If there's no `__init__.py` in the hal folder, what is in there?

**Comment by virtuald** [comment]
Also, you previously had the 32-bit python installed, are you 100% sure that it was uninstalled? It's possible that remnants of the old environment are still around. You should verify that your stack trace has the right path in it (eg, hal should be in your 64-bit site-packages).

**Comment by Trent1048** [comment]
The commands you just typed worked, thanks. (now I need to figure out what's wrong with my own code 😦)

**Comment by auscompgeek** [comment]
This all sounds like you installed at least parts of RobotPy 2020 before the required uninstallation… which then broke your robotpy-hal installation.
